services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot
      POSTGRES_DB: chatbotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://chatbot:chatbot@db:5432/chatbotdb
      SECRET_KEY: your_secret_key
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: